[package]
name        = "dev.peios.librsi-devel"
description = "Peios registry-source C ABI library development files"

[provides]
librsi-devel = "{{version}}-1"

[dependencies]
"dev.peios.librsi" = "= {{version}}-1"
# Public librsi headers include the Peios kernel UAPI under <pkm/lcs.h>.
kernel-headers = ">= 0.20.1-rc2"

[files]
"@source:LICENSE"                              = "usr/share/licenses/dev.peios.librsi-devel/LICENSE"
":usr/include/**"                              = "usr/include"
":usr/lib/x86_64-linux-peios/librsi.so"        = "usr/lib/x86_64-linux-peios/librsi.so"
":usr/lib/x86_64-linux-peios/pkgconfig/rsi.pc" = "usr/lib/x86_64-linux-peios/pkgconfig/rsi.pc"
