[package]
name        = "dev.peios.librsi"
description = "Peios registry-source C ABI library"


[files]
"@source:LICENSE"                         = "usr/share/licenses/dev.peios.librsi/LICENSE"
":usr/lib/x86_64-linux-peios/librsi.so.0" = "usr/lib/x86_64-linux-peios/librsi.so.0"
