/* @generated by cbindgen from the Rust source — do not edit. */

#ifndef RSI_ABI_GENERATED_H
#define RSI_ABI_GENERATED_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>
#include <pkm/lcs.h>

struct rsi_request {
  uint64_t request_id;
  uint64_t txn_id;
  const void *payload;
  uint32_t payload_len;
  uint16_t op_code;
};

struct rsi_hive {
  const void *name;
  uint32_t name_len;
  uint32_t flags;
  uint8_t root_guid[16];
  uint8_t scope_guid[16];
};

struct rsi_transaction {
  uint64_t transaction_id;
};

struct rsi_begin_transaction {
  uint64_t transaction_id;
  uint32_t mode;
};

struct rsi_create_entry {
  uint8_t parent_guid[16];
  uint8_t child_guid[16];
  const void *child_name;
  uint32_t child_name_len;
  const void *layer_name;
  uint32_t layer_name_len;
  uint64_t sequence;
};

struct rsi_create_key {
  uint8_t guid[16];
  uint8_t parent_guid[16];
  const void *name;
  uint32_t name_len;
  const void *sd;
  uint32_t sd_len;
  uint8_t volatile_key;
  uint8_t symlink;
};

struct rsi_delete_entry {
  uint8_t parent_guid[16];
  const void *child_name;
  uint32_t child_name_len;
  const void *layer_name;
  uint32_t layer_name_len;
};

struct rsi_name {
  const void *name;
  uint32_t name_len;
};

struct rsi_delete_value_entry {
  uint8_t guid[16];
  const void *value_name;
  uint32_t value_name_len;
  const void *layer_name;
  uint32_t layer_name_len;
};

struct rsi_key_guid {
  uint8_t guid[16];
};

struct rsi_enum_children {
  uint8_t parent_guid[16];
};

struct rsi_hide_entry {
  uint8_t parent_guid[16];
  const void *child_name;
  uint32_t child_name_len;
  const void *layer_name;
  uint32_t layer_name_len;
  uint64_t sequence;
};

struct rsi_lookup {
  uint8_t parent_guid[16];
  const void *child_name;
  uint32_t child_name_len;
};

struct rsi_query_values {
  uint8_t guid[16];
  const void *value_name;
  uint32_t value_name_len;
  uint8_t query_all;
};

struct rsi_set_blanket_tombstone {
  uint8_t guid[16];
  const void *layer_name;
  uint32_t layer_name_len;
  uint8_t set;
  uint64_t sequence;
};

struct rsi_set_value {
  uint8_t guid[16];
  const void *value_name;
  uint32_t value_name_len;
  const void *layer_name;
  uint32_t layer_name_len;
  uint32_t value_type;
  const void *data;
  uint32_t data_len;
  uint64_t sequence;
  uint64_t expected_sequence;
};

struct rsi_write_key {
  uint8_t guid[16];
  uint32_t field_mask;
  const void *sd;
  uint32_t sd_len;
  uint64_t last_write_time;
};

struct rsi_path_entry {
  const void *layer;
  uint32_t layer_len;
  uint8_t target_type;
  uint8_t target_guid[16];
  uint64_t sequence;
};

struct rsi_child_entry {
  const void *child_name;
  uint32_t child_name_len;
  const struct rsi_path_entry *entries;
  uint32_t entry_count;
};

struct rsi_key_metadata {
  uint8_t guid[16];
  const void *sd;
  uint32_t sd_len;
  uint8_t volatile_key;
  uint8_t symlink;
  uint64_t last_write_time;
};

struct rsi_value_entry {
  const void *value_name;
  uint32_t value_name_len;
  const void *layer_name;
  uint32_t layer_name_len;
  uint32_t value_type;
  const void *data;
  uint32_t data_len;
  uint64_t sequence;
};

struct rsi_blanket_entry {
  const void *layer_name;
  uint32_t layer_name_len;
  uint64_t sequence;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int rsi_parse_request(const void *frame, size_t len, struct rsi_request *out);

ssize_t rsi_read_request(int fd, void *buf, size_t cap);

int rsi_register(const struct rsi_hive *hives, uint32_t count, uint64_t max_sequence);

int rsi_request_abort_transaction(const struct rsi_request *req, struct rsi_transaction *out);

int rsi_request_begin_transaction(const struct rsi_request *req, struct rsi_begin_transaction *out);

int rsi_request_commit_transaction(const struct rsi_request *req, struct rsi_transaction *out);

int rsi_request_create_entry(const struct rsi_request *req, struct rsi_create_entry *out);

int rsi_request_create_key(const struct rsi_request *req, struct rsi_create_key *out);

int rsi_request_delete_entry(const struct rsi_request *req, struct rsi_delete_entry *out);

int rsi_request_delete_layer(const struct rsi_request *req, struct rsi_name *out);

int rsi_request_delete_value_entry(const struct rsi_request *req,
                                   struct rsi_delete_value_entry *out);

int rsi_request_drop_key(const struct rsi_request *req, struct rsi_key_guid *out);

int rsi_request_enum_children(const struct rsi_request *req, struct rsi_enum_children *out);

int rsi_request_flush(const struct rsi_request *req, struct rsi_name *out);

int rsi_request_hide_entry(const struct rsi_request *req, struct rsi_hide_entry *out);

int rsi_request_lookup(const struct rsi_request *req, struct rsi_lookup *out);

int rsi_request_query_values(const struct rsi_request *req, struct rsi_query_values *out);

int rsi_request_read_key(const struct rsi_request *req, struct rsi_key_guid *out);

int rsi_request_set_blanket_tombstone(const struct rsi_request *req,
                                      struct rsi_set_blanket_tombstone *out);

int rsi_request_set_value(const struct rsi_request *req, struct rsi_set_value *out);

int rsi_request_write_key(const struct rsi_request *req, struct rsi_write_key *out);

int rsi_respond_delete_layer(int fd,
                             const struct rsi_request *req,
                             const uint8_t *orphaned_guids,
                             uint32_t orphaned_count);

int rsi_respond_enum_children(int fd,
                              const struct rsi_request *req,
                              const struct rsi_child_entry *children,
                              uint32_t child_count,
                              const struct rsi_key_metadata *metadata,
                              uint32_t metadata_count);

int rsi_respond_lookup(int fd,
                       const struct rsi_request *req,
                       const struct rsi_path_entry *entries,
                       uint32_t entry_count,
                       const struct rsi_key_metadata *metadata,
                       uint32_t metadata_count);

int rsi_respond_query_values(int fd,
                             const struct rsi_request *req,
                             const struct rsi_value_entry *entries,
                             uint32_t entry_count,
                             const struct rsi_blanket_entry *blankets,
                             uint32_t blanket_count);

int rsi_respond_read_key(int fd,
                         const struct rsi_request *req,
                         const void *name,
                         uint32_t name_len,
                         const uint8_t *parent_guid,
                         const void *sd,
                         uint32_t sd_len,
                         uint8_t volatile_key,
                         uint8_t symlink,
                         uint64_t last_write_time);

int rsi_respond_status(int fd, const struct rsi_request *req, uint32_t status);

ssize_t rsi_write_response(int fd, const void *frame, size_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RSI_ABI_GENERATED_H */
